UI in Relaxation relativ zu Position des Nutzers changed
BP-28-FearVR/FearOfHeights pull request #117
Opened 2024-01-28 21:00 UTC by Adotitan

### **Leitfaden für manuellen Test**
### Manueller Test:

- [ ] Sind die Akzeptanzkriterien vollständig und erfüllt?
- [ ] Sind alle Debug-Objekte entfernt?
- [ ] Sind alle Änderungen zielführend für die Akzeptanzkriterien?
- [ ] Beschränken sich die Veränderungen auf das, was von den Akzeptanzkriterien vorgegeben wird (also keine unbeabsichtigten Veränderungen)?
- [ ] Ist es frei von Bugs und andere Fehlern?(nur oberflächlich überprüfen)
- [ ] Ist die bisherige Funktionalität unberührt?
- [ ] Funktionieren die Features wie erwartet für die APK?

2024-01-31 14:16 UTC, dmc1011 requested changes
Die UI erscheint zwar dort wo man hinschaut, aber ist nicht zur Blickrichtung des Nutzers ausgerichtet -> Rotation der UI einbauen

Die Funktionalität muss auch in der zweiten Relaxation Szene eingebaut werden (Szene 3).

Die UI soll immer auf der gleichen Höhe erscheinen, aktuell erscheint sie im Himml oder im Boden wenn man nach oben/unten schaut.

2024-01-31 20:18 UTC, TheMagehawk commented
Am besten auch noch die Whitespaces im Filename entfernen.

Das kann sonst potentiell zu Path Errors führen.

2024-02-08 21:31 UTC, dmc1011 requested changes
Der Code muss nochmal überarbeitet werden

2024-02-08 21:31 UTC, dmc1011 commented on Assets/Script/PositioningTheUI.cs
> +
Variablen als private Klassenattribute definieren, dann erst ein Start() initialisieren

2024-02-08 21:31 UTC, dmc1011 commented on Assets/Script/PositioningTheUI.cs
> +{
Nicht public deklarieren -> entweder private oder SerializeField falls man die Variablen im Editor anpassen können soll

2024-02-08 21:31 UTC, dmc1011 commented on Assets/Script/PositioningTheUI.cs
> +        else
Debug entfernen -> dadurch kann ganzer else Block entfernt werden

2024-02-08 21:31 UTC, dmc1011 commented on Assets/Script/PositioningTheUI.cs
> +            // Calculate a horizontal rotation based on the user's rotation
die Rotation muss meines Wissens nach nicht in horizontalRotation zwischengespeichert werden, sondern kann direkt an transform.rotation übergeben werden (correct me if I´m wrong)

2024-02-08 21:31 UTC, dmc1011 commented on Assets/Script/PositioningTheUI.cs
> +            InputTracking.GetNodeStates(new List<XRNodeState>());
InputTracking ist veraltet -> siehe Projektwarnung/Warnung in Visual Studio Code, Ersatz wird dort vorgeschlagen

2024-02-08 21:31 UTC, dmc1011 commented on Assets/Script/PositioningTheUI.cs
> +        {
die gesamte Funktionalität könnte zur Übersichtlichkeit in eine separate Funktion ausgelagert werden, sodass in der if-Abfrage nur diese eine Funktion aufgerufen wird

2024-02-08 21:51 UTC, dmc1011 requested changes
Das Feature funktioniert nicht in Szene 3 (ich gehe davon aus, es wurde vergessen einzubinden), In Szene 1 funktioniert es gut, vielleicht könnte die UI aber etwas höher (mehr auf Augenhöhe) positioniert sein, vlt ca. 30 cm weiter oben

In Szene 3 dran denken, dass auch das zweite Fenster auf einer neuen Position erscheinen soll (genau an der gleichen Stelle wie das UI Fenster)

2024-02-10 16:05 UTC, TheMagehawk commented
# Leitfaden für manuellen Test
## Manueller Test:
- [ ] Sind die Akzeptanzkriterien vollständig und erfüllt?
- [x] Sind alle Debug-Objekte entfernt?
- [ ] Sind alle Änderungen zielführend für die Akzeptanzkriterien?
- [ ] Beschränken sich die Veränderungen auf das, was von den Akzeptanzkriterien vorgegeben wird (also keine unbeabsichtigten Veränderungen)?
- [ ] Ist es frei von Bugs und andere Fehlern?
- [x] (nur oberflächlich überprüfen) Ist die bisherige Funktionalität unberührt?
- [ ] Funktionieren die Features wie erwartet für die APK?

# Code Review Checkliste
## Struktur
- [ ] Implementiert der Code das Design vollständig und korrekt gemäß den
Akzeptanzkriterien?
- [x] Sind die Variablen- und Methodennamen aussagekräftig?
- [x] Sind die Bezeichner suchbar und aussprechbar?
- [x] Ist der Code gut strukturiert und konsistent in Bezug auf Stil und Formatierung?
- [x] Es gibt keinen unerreichbaren, unbenötigten oder unverwendeten Code.
- [ ] Es gibt keine Überreste von Testroutinen, Debugging, etc.
- [ ] Es gibt keine Codefragmente, die durch extern definierte, wiederverwendbare Komponenten oder Funktionen ersetzt werden können.
- [x] Es gibt keine Wiederholungen im Code, die in eine Methode/Funktion ausgelagert werden können.
- [ ] Ist die Speichernutzung vertretbar?
- [x] Es werden nicht unnötig viele Objekte Instanzieiert. (Also 'new' z.B. jedes Update - nur falls unbedingt nötig)
- [x] Falls einzelne Module/Konstrukte zu komplex sind, werden diese in kleinere Module aufgeteilt/ausgelagert.
- [x] Wird Hard Coding vermieden?
- [x] Werden Namespaces korrekt verwendet und mit using-Direktiven eingebunden?
- [ ] Sind alle ungenutzten using-Direktiven entfernt worden?
- [x] Existiert nur maximal eine MonoBehaviour-Klasse pro Datei?
- [x] Falls ein MonoBehaviour in einer Datei existiert, besitzt die Datei den gleichen Namen?
- [ ] Von dem Code wird keine Projektwarnung erzeugt.

## Dokumentation

- [x] Ist der Code verständlich und angemessen kommentiert?
- [x] Ist der Stil der Kommentare übersichtlich, einheitlich und leicht zu warten?


## Variablen

- [x] Es gibt keine redundanten oder nicht verwendeten Variablen?
- [x] Entsprechen die Variablen konsistent den selben Typen?
- [ ] Sind die Variablen mit dem korrektem Zugriffslevel deeklariert (private/public/...)?
- [ ] Wird die Deklaration als [SerializeField] gegenüber public bevorzugt, falls ein Zugriff durch den Editor, aber nicht von außerhalb der Klasse möglich sein soll?

## Arithmetische Operationen

- [x] Vermeidet der Code das Vergleichen von Floating-Point Zahlen?
- [x] Verhindert der Code Rundungsfehler?
- [x] Wird Division durch Null ausgeschlossen?

## Schleifen und Verzweigungen

- [ ] Sind alle Schleifen, Verzweigungen und andere logischen Konstrukte vollständig, korrekt und vernünftig geschachtelt?
- [x] Werden in if-else-Verkettungen (o.ä.) die wahrscheinlichsten Fälle als erstes getestet?
- [x] Werden in if-else-Verkettungen (o.ä.) alle relevanten Fälle abgedeckt (insbesondere else und default)?
- [x] Hat jedes case-Statement eine default-Anweisung?
- [x] Sind die Terminierungsbedingungen für Schleifen verständlich und terminieren die Schleifen ausnahmslos?
- [x] Sind Indizes korrekt und intuitiv initialisiert (unmittelbar vor der Schleife)?
- [x] Es gib keine Statements in einer Schleife, die stattdessen außerhalb der Schleife platziert werden können.
- [x] Vermeidet der Code, die Indexvariable zu verändern oder nach Terminierung der Schleife zu verwenden?

## Defensives Programmieren

- [x] Werden Indizes (o.ä.) auf Grenzen getestet (Arrays, Files, ...)?
- [x] Werden importierte Daten und Input-Argumente auf Gültigkeit und Vollständigkeit getestet
- [x] Sind alle Output-Variablen zugewiesen?
- [x] Wird in jedem Statement auf den richtigen Daten operiert?
- [x] Werden Files auf Existenz geprüft, bevor auf sie zugegriffen wird?
- [x] Werden alle Files und Devices in korrektem Zustand verlassen, wenn das Programm terminiert?

## Style Guide
- [ ] Entspricht der Code den Codingstandards?
  - [x] Sind lokale Variablen und Parameter in Camel Case benannt?
  - [x] Werden private Attribute mit einem (\_)-Präfix gekennzeichnet, um sie von lokalen Variablen zu unterscheiden? (\_count, \_delay)
  - [x] Werden für Variablenbezeichner primär Nomen verwendet? (Ausnahme: bool)
  - [x] Werden für boolsche Variablen ein Verb-Prefix verwendet? (isAlive, hasStarted)
  - [x] Sind public fields, Enums, Methoden, Namespaces und Klassen in Pascal Case benannt?
  - [x] Werden für Methodenbezeichner primär Verben verwendet? (GetDirection, FindTarget)
  - [x] Werden übermäßige Abkürzungen in Bezeichnern vermieden? (Ausnahme: Maths)
  - [x] Sind Kommentare in Englisch verfasst?
  - [x] Werden Events mit einer Verb-Phrase im der richtigen Zeitform (present vs past participle) benannt? (OpeningDoor, DoorOpened)
  - [x] Werden Methoden, die sich auf ein Event beziehen, mit dem Präfix "On" benannt? (OnDoorOpened)

2024-02-10 16:09 UTC, TheMagehawk commented
# Leitfaden für manuellen Test
## Manueller Test:
- [ ] Sind die Akzeptanzkriterien vollständig und erfüllt?
- [x] Sind alle Debug-Objekte entfernt?
- [ ] Sind alle Änderungen zielführend für die Akzeptanzkriterien?
- [ ] Beschränken sich die Veränderungen auf das, was von den Akzeptanzkriterien vorgegeben wird (also keine unbeabsichtigten Veränderungen)?
- [ ] Ist es frei von Bugs und andere Fehlern?
- [x] (nur oberflächlich überprüfen) Ist die bisherige Funktionalität unberührt?
- [ ] Funktionieren die Features wie erwartet für die APK?

# Code Review Checkliste
## Struktur
- [ ] Implementiert der Code das Design vollständig und korrekt gemäß den
Akzeptanzkriterien?
- [x] Sind die Variablen- und Methodennamen aussagekräftig?
- [x] Sind die Bezeichner suchbar und aussprechbar?
- [x] Ist der Code gut strukturiert und konsistent in Bezug auf Stil und Formatierung?
- [x] Es gibt keinen unerreichbaren, unbenötigten oder unverwendeten Code.
- [ ] Es gibt keine Überreste von Testroutinen, Debugging, etc.
- [ ] Es gibt keine Codefragmente, die durch extern definierte, wiederverwendbare Komponenten oder Funktionen ersetzt werden können.
- [x] Es gibt keine Wiederholungen im Code, die in eine Methode/Funktion ausgelagert werden können.
- [ ] Ist die Speichernutzung vertretbar?
- [x] Es werden nicht unnötig viele Objekte Instanzieiert. (Also 'new' z.B. jedes Update - nur falls unbedingt nötig)
- [x] Falls einzelne Module/Konstrukte zu komplex sind, werden diese in kleinere Module aufgeteilt/ausgelagert.
- [x] Wird Hard Coding vermieden?
- [x] Werden Namespaces korrekt verwendet und mit using-Direktiven eingebunden?
- [ ] Sind alle ungenutzten using-Direktiven entfernt worden?
- [x] Existiert nur maximal eine MonoBehaviour-Klasse pro Datei?
- [x] Falls ein MonoBehaviour in einer Datei existiert, besitzt die Datei den gleichen Namen?
- [ ] Von dem Code wird keine Projektwarnung erzeugt.

## Dokumentation

- [x] Ist der Code verständlich und angemessen kommentiert?
- [x] Ist der Stil der Kommentare übersichtlich, einheitlich und leicht zu warten?


## Variablen

- [x] Es gibt keine redundanten oder nicht verwendeten Variablen?
- [x] Entsprechen die Variablen konsistent den selben Typen?
- [ ] Sind die Variablen mit dem korrektem Zugriffslevel deeklariert (private/public/...)?
- [ ] Wird die Deklaration als [SerializeField] gegenüber public bevorzugt, falls ein Zugriff durch den Editor, aber nicht von außerhalb der Klasse möglich sein soll?

## Arithmetische Operationen

- [x] Vermeidet der Code das Vergleichen von Floating-Point Zahlen?
- [x] Verhindert der Code Rundungsfehler?
- [x] Wird Division durch Null ausgeschlossen?

## Schleifen und Verzweigungen

- [ ] Sind alle Schleifen, Verzweigungen und andere logischen Konstrukte vollständig, korrekt und vernünftig geschachtelt?
- [x] Werden in if-else-Verkettungen (o.ä.) die wahrscheinlichsten Fälle als erstes getestet?
- [x] Werden in if-else-Verkettungen (o.ä.) alle relevanten Fälle abgedeckt (insbesondere else und default)?
- [x] Hat jedes case-Statement eine default-Anweisung?
- [x] Sind die Terminierungsbedingungen für Schleifen verständlich und terminieren die Schleifen ausnahmslos?
- [x] Sind Indizes korrekt und intuitiv initialisiert (unmittelbar vor der Schleife)?
- [x] Es gib keine Statements in einer Schleife, die stattdessen außerhalb der Schleife platziert werden können.
- [x] Vermeidet der Code, die Indexvariable zu verändern oder nach Terminierung der Schleife zu verwenden?

## Defensives Programmieren

- [x] Werden Indizes (o.ä.) auf Grenzen getestet (Arrays, Files, ...)?
- [x] Werden importierte Daten und Input-Argumente auf Gültigkeit und Vollständigkeit getestet
- [x] Sind alle Output-Variablen zugewiesen?
- [x] Wird in jedem Statement auf den richtigen Daten operiert?
- [x] Werden Files auf Existenz geprüft, bevor auf sie zugegriffen wird?
- [x] Werden alle Files und Devices in korrektem Zustand verlassen, wenn das Programm terminiert?

## Style Guide
- [ ] Entspricht der Code den Codingstandards?
  - [x] Sind lokale Variablen und Parameter in Camel Case benannt?
  - [x] Werden private Attribute mit einem (\_)-Präfix gekennzeichnet, um sie von lokalen Variablen zu unterscheiden? (\_count, \_delay)
  - [x] Werden für Variablenbezeichner primär Nomen verwendet? (Ausnahme: bool)
  - [x] Werden für boolsche Variablen ein Verb-Prefix verwendet? (isAlive, hasStarted)
  - [x] Sind public fields, Enums, Methoden, Namespaces und Klassen in Pascal Case benannt?
  - [x] Werden für Methodenbezeichner primär Verben verwendet? (GetDirection, FindTarget)
  - [x] Werden übermäßige Abkürzungen in Bezeichnern vermieden? (Ausnahme: Maths)
  - [x] Sind Kommentare in Englisch verfasst?
  - [x] Werden Events mit einer Verb-Phrase im der richtigen Zeitform (present vs past participle) benannt? (OpeningDoor, DoorOpened)
  - [x] Werden Methoden, die sich auf ein Event beziehen, mit dem Präfix "On" benannt? (OnDoorOpened)

2024-02-10 16:10 UTC, TheMagehawk approved these changes

2024-02-10 16:35 UTC, dmc1011 requested changes

2024-02-10 16:35 UTC, dmc1011 commented on Assets/Script/PositioningTheUI.cs
> +public class PositioningtheUI : MonoBehaviour
Die Klasse muss benannt sein, wie die Datei

2024-02-10 16:35 UTC, dmc1011 commented on Assets/Script/PositioningTheUI.cs
> +{
SerializeFields werden nicht mit _ benannt, den _ schreibt man nur am Anfang der Namen wenn die Variable ein rein privates Klassenattribut ist

2024-02-10 16:35 UTC, dmc1011 commented on Assets/Script/PositioningTheUI.cs
> +            {
Keine Debug Anweisungen

2024-02-10 16:35 UTC, dmc1011 commented on Assets/Script/PositioningTheUI.cs
> +
Vorschlag für Methodenname: HasUIPositionAndRotationBeenSet (weil es eine boolsche Methode ist)

2024-02-10 22:24 UTC, dmc1011 approved these changes
passt

2024-02-10 22:24 UTC, merged