UI Single Text Prefab im Ordner Prefabs\UI hinzugefügt.
BP-28-FearVR/FearOfHeights pull request #38
Opened 2023-12-13 17:57 UTC by dmc1011

2023-12-14 12:57 UTC, Sigma42 requested changes
Es gibt änderungen in Scene 0.

Wenn ich es richtig sehe schon 24 etwas umgesetzt?
Die müssten noch raus.

2023-12-15 15:46 UTC, Sigma42 approved these changes

2023-12-15 15:47 UTC, Besteresis commented
sieht gut aus

2023-12-15 15:48 UTC, Besteresis approved these changes
sieht gut aus

2023-12-15 15:48 UTC, merged